# Generated by Django 5.1.3 on 2024-12-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_question_created_at_question_ticket_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="ticket_type",
            new_name="ticket",
        ),
    ]
