# Generated by Django 5.1.3 on 2025-03-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_rename_ticket_type_question_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
